import { StyleSheet } from "react-native";

const cardShadowStyle = {
  shadowColor: "blue",
  shadowOffset: { width: 0, height: 8 },
  shadowOpacity: 0.12,
  shadowRadius: 24,
  elevation: 8,
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  scrollView: {
    flex: 1,
  },
  header: {
    backgroundColor: "white",
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 34,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: "black",
    marginBottom: 8,
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 16,
    color: "black",
    fontWeight: "500",
  },
  content: {
    flex: 1,
    backgroundColor: "white",
    marginTop: -16,
  },
  formContainer: {
    flex: 1,
    paddingHorizontal: 20,
    paddingBottom: 20,
    paddingTop: 20,
  },
  selectionCard: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 20,
    marginBottom: 10,
    borderWidth: 1,
    ...cardShadowStyle,
  },
  selectionCardContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  selectionIcon: {
    width: 56,
    height: 56,
    backgroundColor: "white",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  selectionText: {
    flex: 1,
  },
  selectionSubtitle: {
    color: "#64748b",
    fontSize: 14,
    fontWeight: "600",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  selectionTitle: {
    color: "#1e293b",
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 24,
  },
  searchButton: {
    backgroundColor: "#10b981",
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 8,
  },
  searchButtonText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "700",
    letterSpacing: 0.5,
  },
  loadingContainer: {
    marginTop: 40,
    flex: 1,
    backgroundColor: "white",

    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    fontSize: 18,
    color: "#64748b",
    marginTop: 12,
    fontWeight: "500",
  },
  // Enhanced Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: "white",
  },
  modalHeader: {
    backgroundColor: "white",

    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 24,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    ...cardShadowStyle,
  },
  modalHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  closeButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 22,
    backgroundColor: "#f1f5f9",
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1e293b",
    flex: 1,
    textAlign: "center",
    marginLeft: 5,
  },
  modalScrollView: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  cityContainer: {
    marginBottom: 24,
  },
  cityHeader: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 20,
    marginBottom: 16,
    borderWidth: 0,
    ...cardShadowStyle,
  },
  cityHeaderContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cityInfo: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  cityIcon: {
    width: 48,
    height: 48,
    backgroundColor: "white",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 5,
  },
  cityName: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1e293b",
    flex: 1,
  },
  cityMeta: {
    flexDirection: "row",
    alignItems: "center",
  },
  stationCount: {
    fontSize: 14,
    color: "#64748b",
    fontWeight: "600",
    backgroundColor: "#f1f5f9",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  stationsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 2,
  },
  stationCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 16,
    minWidth: "45%",
    borderWidth: 2,
    borderColor: "#f1f5f9",
    ...cardShadowStyle,
  },
  selectedStationCard: {
    borderColor: "#10b981",
    backgroundColor: "#ecfdf5",
  },
  stationName: {
    fontWeight: "600",
    color: "#374151",
    fontSize: 15,
    textAlign: "center",
  },
  selectedStationName: {
    color: "#059669",
    fontWeight: "700",
  },
  // Enhanced Results styles
  resultsContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 24,
    padding: 24,
    marginHorizontal: 20,
    marginTop: 24,
    ...cardShadowStyle,
  },
  resultsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  resultsTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: "#1e293b",
    flex: 1,
  },
  newResultsBadge: {
    backgroundColor: "#dcfce7",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  newResultsText: {
    color: "#166534",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  tripsList: {
    gap: 20,
  },
  // Enhanced Trip Card Styles
  enhancedTripCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 0,
    marginBottom: 20,
    borderWidth: 0,
    overflow: "hidden",
    ...cardShadowStyle,
  },
  tripCardHeader: {
    backgroundColor: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)",
    padding: 20,
  },
  tripRoute: {
    marginBottom: 20,
  },
  routePoint: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  routeDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#ffffff",
    marginRight: 16,
  },
  routeLine: {
    width: 2,
    height: 24,
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    marginLeft: 5,
    marginBottom: 8,
  },
  locationText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#ffffff",
    flex: 1,
  },
  tripCardContent: {
    padding: 20,
  },
  // Trip Times Container
  tripTimesContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
  },
  timeItem: {
    alignItems: "center",
    flex: 1,
  },
  timeLabel: {
    fontSize: 12,
    color: "#64748b",
    fontWeight: "600",
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  timeValue: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1e293b",
  },
  durationContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  durationText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#4f46e5",
    marginLeft: 6,
  },
  // Trip Details Grid
  tripDetailsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  detailItem: {
    width: "48%",
    backgroundColor: "#f8fafc",
    padding: 16,
    borderRadius: 16,
    marginBottom: 12,
  },
  detailLabel: {
    fontSize: 12,
    color: "#64748b",
    textTransform: "uppercase",
    fontWeight: "600",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  detailValue: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1e293b",
  },
  seatsContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
  },
  seatsText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#059669",
    marginLeft: 6,
  },
  // Trip Footer
  tripFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#f1f5f9",
  },
  priceSection: {
    alignItems: "flex-start",
    flex: 1,
  },
  priceText: {
    fontSize: 28,
    fontWeight: "800",
    color: "#059669",
    letterSpacing: -0.5,
  },
  priceSubtext: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 4,
    fontWeight: "500",
  },
  availabilityBadge: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: "#dcfce7",
  },
  availabilityText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#166534",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bookButton: {
    backgroundColor: "linear-gradient(135deg, #10b981 0%, #059669 100%)",
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: "center",
    marginTop: 16,
    ...cardShadowStyle,
  },
  bookButtonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.5,
  },
  // No results
  noResultsContainer: {
    alignItems: "center",
    paddingVertical: 48,
    backgroundColor: "#ffffff",
    borderRadius: 20,
    marginHorizontal: 20,
    marginTop: 24,
    ...cardShadowStyle,
  },
  noResultsIcon: {
    width: 80,
    height: 80,
    backgroundColor: "#f1f5f9",
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 20,
  },
  noResultsTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: 8,
  },
  noResultsSubtitle: {
    fontSize: 15,
    color: "#64748b",
    textAlign: "center",
    paddingHorizontal: 32,
    lineHeight: 22,
  },
  errorContainer: {
    backgroundColor: "#fef2f2",
    borderLeftWidth: 4,
    borderLeftColor: "#ef4444",
    padding: 20,
    marginHorizontal: 20,
    marginTop: 20,
    borderRadius: 16,
    ...cardShadowStyle,
  },
  errorText: {
    color: "#dc2626",
    fontSize: 15,
    fontWeight: "600",
  },
});

export default styles;
